language: node_js
node_js:
- '0.10'
install: npm install
before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
after_success:
  - bash scripts/output_coverage.sh | ./node_modules/codeclimate-test-reporter/bin/codeclimate.js
  - bash scripts/output_coverage.sh | ./node_modules/coveralls/bin/coveralls.js
addons:
  code_climate:
    repo_token: 92531c4b8fb81bc39f5429fbbf263186553abef4c0720a94f0bbc3fe195d9986
